# Generated by Django 4.2.7 on 2025-04-12 21:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to='products/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Цена должна быть больше нуля')], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(decimal_places=1, default=Decimal('6.1'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.0'), message='Диагональ экрана должна быть больше 1 дюйма'), django.core.validators.MaxValueValidator(Decimal('20.0'), message='Диагональ экрана должна быть меньше 20 дюймов')], verbose_name='Диагональ экрана (дюймы)'),
        ),
    ]
