# Generated by Django 4.2.7 on 2025-05-01 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='includes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='screen_size',
        ),
        migrations.AddField(
            model_name='product',
            name='turbo',
            field=models.BooleanField(default=False, verbose_name='Наличие турбо'),
        ),
        migrations.AddField(
            model_name='product',
            name='комплектация',
            field=models.JSONField(default=list, help_text='Список комплектующих', verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='body_condition',
            field=models.CharField(choices=[('A', 'Идеальное'), ('B', 'Хорошее'), ('C', 'Удовлетворительное'), ('D', 'Плохое')], default='B', max_length=20, verbose_name='Состояние корпуса'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Чёрный'), ('white', 'Белый'), ('gold', 'Золотой'), ('silver', 'Серебристый'), ('blue', 'Синий'), ('red', 'Красный'), ('green', 'Зелёный'), ('other', 'Другой')], max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone_model',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_phone_model', message='Модель телефона может содержать только буквы, цифры и специальные символы', regex='^[a-zA-Zа-яА-Я0-9\\s\\-_.,!?()]+$')], verbose_name='Модель телефона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_condition',
            field=models.CharField(choices=[('A', 'Идеальное'), ('B', 'Хорошее'), ('C', 'Удовлетворительное'), ('D', 'Плохое')], default='B', max_length=20, verbose_name='Состояние экрана'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], max_length=50, verbose_name='Память'),
        ),
    ]
