# Generated by Django 4.2.7 on 2025-05-01 23:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_includes_remove_product_screen_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1')), django.core.validators.MaxValueValidator(Decimal('10.0'))], verbose_name='Размер экрана (дюймы)'),
        ),
    ]
