# Generated by Django 4.2.7 on 2025-04-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_main_image_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.IntegerField(default=1, verbose_name='ID продавца'),
        ),
    ]
