# Generated by Django 4.2.7 on 2025-05-06 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_screen_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_number',
            field=models.CharField(default=1, help_text='Формат: +7 (999) 999-99-99', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Введите номер телефона в формате +7 (999) 999-99-99', regex='^\\+7\\s?\\(\\d{3}\\)\\s?\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
