# Generated by Django 4.2.7 on 2025-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_display_alter_product_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='комплектация',
            new_name='package_contents',
        ),
    ]
