# Generated by Django 4.2.7 on 2025-05-11 01:35

from django.db import migrations, models
import django.db.models.deletion

def remove_existing_media_images(apps, schema_editor):
    MediaImage = apps.get_model('products', 'MediaImage')
    MediaImage.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_комплектация_product_package_contents'),
    ]

    operations = [
        migrations.RunPython(remove_existing_media_images),
        migrations.AddField(
            model_name='mediaimage',
            name='product',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='products.product'),
        ),
    ]
