# Generated by Django 4.2.7 on 2025-05-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_mediaimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_images', to='products.product'),
        ),
    ]
