# Generated by Django 4.2.7 on 2025-05-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_fix_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media Image', 'verbose_name_plural': 'Media Images'},
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
