# Generated by Django 5.0.2 on 2025-05-26 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_mediaimage_options_mediaimage_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimage',
            name='image',
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='image_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='additional_products', to='products.mediaimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Название может содержать только буквы, цифры и специальные символы', regex='^[a-zA-Z0-9\\s\\-_.,!?()]+$')], verbose_name='Название'),
        ),
    ]
