# Generated by Django 4.2.7 on 2025-05-27 21:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_mediaimage_image_mediaimage_image_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.mediaimage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(db_index=True, max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_title', message='Название может содержать только буквы, цифры и специальные символы', regex='^[a-zA-Z0-9\\s\\-_.,!?()]+$')], verbose_name='Название'),
        ),
    ]
