# Generated by Django 4.2.7 on 2025-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_main_image_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_top', '-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(db_index=True, default=False, verbose_name='В топе'),
        ),
    ]
