# Generated by Django 4.2.7 on 2025-07-12 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_options_product_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Город'),
        ),
    ]
