# Generated by Django 5.0.2 on 2025-07-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimage',
            name='image_data',
        ),
        migrations.RemoveField(
            model_name='mediaimage',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='main_image_type',
        ),
        migrations.AddField(
            model_name='mediaimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/additional/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/main/'),
        ),
    ]
