# Generated by Django 5.0.2 on 2025-07-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_mediaimage_image_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='additional_images',
            new_name='product_images',
        ),
        migrations.AlterField(
            model_name='mediaimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product'),
        ),
    ]
