# Generated by Django 5.0.2 on 2025-07-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_rename_additional_images_product_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaimage',
            name='product',
        ),
    ]
