# Generated by Django 4.2.7 on 2025-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_mediaimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='faults',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='imei',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sim',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
