# Generated by Django 5.0.2 on 2025-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_product_face_product_faults_product_imei_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус обработки изображений'),
        ),
    ]
